Yatekii/imgui-wgpu-rs

Cargo.toml
Fixes Metal build on Mac OS X. I think the feature is derived in webgpu automatically, please double check it works on Vulkan.
=> Fixing wgpu feature hardcoded to ‘vulkan’.

examples/custom_textures.rs, examples/hello_world.rs, src/lib.rs
I just changed the `Ui` parameter to a `&DrawData` one.
This difference make possible the reuse of `DrawData` in your app, which can be very useful when rendering and event_handling are asynchronous.
That was impossible before, because the `ui` was consumed inside the render function with `ui.render()`, which forced the user to recreate `ui` each time it was drawn.
=> change render() parameters

Cargo.lock, Cargo.toml, examples/custom_textures.rs, examples/hello_world.rs
i'm sorry, forgot update winit in examples; i tested with another project it works fine :)
i also accidentally rust formated examples (format on save); i can undo if want but can i just leave it?
=> fix examples to use new winit

Cargo.lock, Cargo.toml, examples/custom_textures.rs, examples/hello_world.rs, src/lib.rs
This is compatible with what's currently on wgpu-rs master, which I believe will become `0.5`.
=> Add compatibility for the next version of wgpu

src/lib.rs
Prevents borrow errors with another library I'm using, and Queue has no `&mut self` methods. Please make a new release after merging this :).
=> Replace &mut Queue with &Queue

Cargo.toml, README.md, examples/custom_textures.rs, examples/hello_world.rs, src/lib.rs
wgpu 0.6 just dropped earlier today, and I know how many people use this library, so I wanted to help out and update this to 0.6!
Besides upgrading to 0.6 I changed a couple performance and QOL related things that have been discovered in the 0.5 -> 0.6 transition.
- Added labels for all things which take labels.
- Remove staging buffers as `queue.write_buffer`/`device.create_buffer_init` now efficiently implement staging buffers automatically.
- Use bytemuck for conversions between types and a pile of bytes. (very small dependency which most users will already depend on)
- Use smallvecs to store vertex/index buffers to save some allocations and keep things on the stack. (wgpu already depends on smallvec, so this is "free")
- Change the api so that users provide their own renderpass. This …
=> Update WGPU to 0.6

examples/cube.rs, examples/custom_textures.rs, examples/hello_world.rs
This PR makes examples to obtain initial scale factor correctly. This affect the initialization of font bitmap.
On MacOS,
Before:
After:
=> fix: initial scale factor

src/lib.rs
That's the only change on imgui-wgpu side necessary to support viewports from docking branch of Dear ImGui.
This change is compatible and works the same with master branch of Dear ImGui and 0.4/0.5 versions of imgui-rs.
=> Add support for viewports

examples/cube.rs, examples/custom_textures.rs, examples/hello_world.rs, src/lib.rs
A texture is now represented by the `Texture` struct.
Its texture data can now be uploaded and updated with `Texture::write()`.
Made the `Renderer::textures` field publicly accessible (it's used to manage existing textures).
Changed `Renderer::reload_font_texture()` to take into account possible preuploaded font atlas textures.
Added some documentation to the `Texture` struct and its methods.
I've also incorporated the commit Aeledfyr@af054c9a21524fed4c8746f06473d852af7790e1 (@Aeledfyr I hope it's OK), which enables to pass a depth format and MSAA sample count when creating a new renderer.
=> Better texture support

examples/cube.rs, examples/custom_textures.rs, examples/hello_world.rs
in 59557269bc7eedf97c4b50ee1a168d6fd6ab4360 I removed the size cause I assumed it only had global effect but it was used locally for the new sc descriptor and after the change never got updated values but always saw the global one
closes https://github.com/Yatekii/imgui-wgpu-rs/issues/36 if confirmed
=> fix regression

.github/workflows/ci.yml, Cargo.toml, examples/basic_simple_api.rs, examples/custom_textures.rs, examples/fullscreen_simple_api.rs, examples/hello_world.rs, src/lib.rs, src/simple_api.rs
Motivation:
- I end up copying the hello world example in multiple places.
- Implot works very well but to make it as easy to use as e..g matplotlib. a simple way to create a context to use imgui in would be helpful. 
Hello World with this api becomes:
```rust
fn main() {
imgui_wgpu::simple_api::run(Default::default(), (), |ui, _| {
imgui::Window::new(imgui::im_str!("hwllo world")).build(&ui, || {
ui.text(imgui::im_str!("Hello world!"));
});
});
}
```
This API pulls in additional dependencies like winit so I added it under a feature flag which makes clear that API stability is not guaranteed to make maintenance easier and updating dependencies easier. Note that even if this breaks users code its still easier for the common case where it does not break and the existing copy paste option …
=> add simple api

src/lib.rs
Implementing `std::error::Error` for `RendererError` lets people use `Renderer::render`  with the `?` operator in a method that returns `Result<(), Box<dyn Error>>`
=> Implement std::error:Error for RendererError

CHANGELOG.md, Cargo.toml, README.md, examples/hello_world.rs
Updating winit dependency to 0.24.
Needs a new release of the `imgui-winit-support` crate first, which in turn needs a new release of `glium`. See https://github.com/imgui-rs/imgui-rs/pull/404
Marking this PR as draft until both have a new release on crates.io
=> Support winit 0.24

CHANGELOG.md, Cargo.toml, examples/cube.rs, examples/custom_textures.rs, examples/hello_world.rs, src/lib.rs, src/simple_api.rs
This bumps version to `0.13` and includes support for wgpu `0.7`. No API changes beyond what was already merged.
=> Update to wgpu 0.7

src/lib.rs
Pass on the sample_count value to the new MultisampleState parameter of the render pipeline.
=> Fix multisampling for wgpu 0.9

CHANGELOG.md, src/lib.rs
Recent clippy versions warn about unnecessary borrows. This PR fixes the new warnings.
=> Fix clippy warnings

CHANGELOG.md, Cargo.toml, examples/cube.rs, examples/custom_textures.rs, examples/hello_world.rs, src/lib.rs, src/simple_api.rs
This PR updates the library to be compatible with wgpu 0.10.
Everything compiles and all the demos run, except for the `cube.rs` demo. It seems to stall out in the `Example::render()` function when submitting the command buffer to the queue. I will need to investigate if this is due to a change in wgpu or just a bug in updating to the latest version.
Because of this unsolved issue this PR is marked as WIP.
Fixes #65
=> Upgrade to wpgu 0.10

README.md
This is required for the top-level user Cargo.toml since wgpu 0.10 to avoid build errors.
Notice is copied from the https://github.com/parasyte/pixels project.
=> Add README note to set `resolver = "2"`

CHANGELOG.md, src/lib.rs
In the `hello_world` example, I can cause a crash by expanding the "Help" section and then resizing the window (the window manager window, not the imgui window) down very small. The crash is caused by the scissor rect extending beyond the framebuffer dimensions.
This PR adds a check for this which is present in both the standard C++ imgui backends (see [here](https://github.com/ocornut/imgui/blob/cf2daf353ebffdc84e081b76fe5112776af8a1f4/backends/imgui_impl_opengl3.cpp#L478)), and in the imgui-rs gfx backend [here](https://github.com/imgui-rs/imgui-rs/blob/master/imgui-gfx-renderer/src/lib.rs#L269).
I believe this fixes some of the crashes mentioned in #53 but not all of them. Check this issue on wgpu for more info on a complete fix: https://github.com/gfx-rs/wgpu/issues/1750
=> Do not perform scissor if outside framebuffer (fixes `Invalid ScissorRect parameters`)

README.md
This fixes the example link in the README 404ing.
=> Fix broken example link in README

README.md
Not applicable, this is a documentation fix.
I am not seeking credit for this, it is a very minor fix.
New users copy-pasting from the README will encounter the following error:
```
$ cargo run --release --example hello_world
error: no example target named `hello_world`
Did you mean `hello-world`?
```
This is a fix for the typo.
None.
=> Fix typo in README quickstart example

CHANGELOG.md, src/lib.rs
For example, if you have your own texture implementation, it can be painful being forced to move the `wgpu::Texture` into `Texture::from_raw_parts`. To workaround this, I changed the type form `wgpu::Texture` to `Arc<wgpu::Texture>` to allow cloning the texture, which allows still having the own texture implementation exist (same for `wgpu::TextureView` & `wgpu::BindGroup`). This is especially useful if you have a texture atlas that is used by ImGui but also used by the own renderer implementation.
=> Make `Texture` take `Arc<T>` instead of `T`  to avoid being forced to move into the texture

CHANGELOG.md, src/lib.rs
Hey, its me again,
I noticed that it can be really painful when you need to create the bind group inside `Texture::from_raw_parts` by yourself. My solution to this is changing the type of `bind_group` from `BindGroup` to `Option<BindGroup>` to allow passing the self-created bind group as a `Some` and using the `None` variant to create the bind group like the `Texture::new` function does.
=> Change `BindGroup` inside `Texture::from_raw_parts` to `Option<BindGroup>` to allow bind group being created by imgui-wgpu-rs

CHANGELOG.md, examples/cube.rs, examples/custom-texture.rs, examples/hello-world.rs
Fixes the resizing logic. Makes sure we create a texture that is of the proper size. The size the callback gets vs what `window.inner_size()` does not match up. ImGui however, uses the correct value and it causes a crash where a scissor bigger than the current texture is attempted.
Perhaps #99 and #77
=> Fix updating of WGPU texture size

CHANGELOG.md, src/lib.rs
Fixes wgpu tp panic because of to big scissor rects. Change limits scissor rect size to the soze of the framebuffer.
=> Pixelboys tm/issue77

CHANGELOG.md, Cargo.toml, examples/cube.rs, examples/custom-texture.rs, examples/hello-world.rs
Supersedes #105 by incorporating #104. The first commit is the actual dependency bump, while the second commit is a simple refactor of the event loop body in the examples to unify the `Event::WindowEvent` match arms, with no other changes. I separated the two for the sake of easier review.
=> Update wgpu to 0.19

CHANGELOG.md, Cargo.toml, deny.toml, examples/cube.rs, examples/custom-texture.rs, examples/hello-world.rs, src/lib.rs
Bumped wgpu to version 22.1. Consists of three commits:
- bumping the dependency version, updating src/lib.rs slightly to the newer version
- Fixing the examples with the new version of wgpu/winit
- Adding skip rules to deny.toml
=> Bump wgpu to 22.1

.github/workflows/build.yml, CHANGELOG.md, Cargo.toml, deny.toml, examples/cube.rs, src/lib.rs
Bump wgpu to version 23.0. The changes are pretty minor, just some fields became optional. Works on my machine!
Also updated cargo-deny config to cope with the breaking changes from [version 16.0](https://github.com/EmbarkStudios/cargo-deny/releases/tag/0.16.0).
=> Update wgpu to 23.0

Cargo.toml, examples/cube.rs, examples/custom-texture.rs, examples/hello-world.rs, src/lib.rs
Updated version from 23.0 to 24.0.1.
I wanted to add imgui into my app but the version of wgpu required for this package broke my app. (myapp uses 24.0.1, the latest version)
I've updated the version of wgpu in the dependency to 24.0.1 and the examples to check that it doesn't cause any issues. ;-)
=> Update wgpu version to 24.0.1

CHANGELOG.md, examples/empty.rs, src/lib.rs
Fix a crash that occurs when submitting an empty draw list, and harden against invalid slice access. Added an example that can be used as a regression test.
Contributing upstream from https://github.com/jbrd/bevy_mod_imgui/pull/57
(originally uncovered in https://github.com/jbrd/bevy_mod_imgui/pull/55).
Issue #114
=> Fix Issue #114 - crash on empty draw list
