- Cargo.lock
- Cargo.toml
- examples/hello_world.rs
- src/lib.rs
* update wgpu api
* update winit and raw-window-handle deps
> update to latest wgpu-rs api

- Cargo.lock
- Cargo.toml
- examples/custom_textures.rs
- examples/hello_world.rs
- src/lib.rs
Continuation of https://github.com/Yatekii/imgui-wgpu-rs/pull/8
Also fixed the hello_world example so window resizing is possible.
> Update for latest wgpu rev 9a67ce1

- Cargo.lock
- Cargo.toml
- examples/custom_textures.rs
- examples/hello_world.rs
- src/lib.rs
@Yatekii 
I'd like to remove the `Cargo.lock` from git and run `rustfmt` on the project with the next update, if that's ok with you.
> Update for latest wgpu rev 7b15e24

- Cargo.toml
- examples/custom_textures.rs
Just bumping up all the versions.
> Bump versions

- Cargo.toml
- examples/cube.rs
- examples/custom_textures.rs
- examples/hello_world.rs
- src/lib.rs
closes https://github.com/Yatekii/imgui-wgpu-rs/issues/22
tested it in my small project with shaderc feature and worked fine
> remove shaderc

- examples/cube.rs
- examples/custom_textures.rs
- examples/hello_world.rs
- src/lib.rs
ref https://github.com/Yatekii/imgui-wgpu-rs/pull/33
happy to make naming changes or other stuff if recommended :)
> switch to struct init for Renderer and Texture creation, like wgpu-rs

- Cargo.toml
- examples/cube.rs
- examples/custom_textures.rs
- examples/hello_world.rs
update imgui to 0.6 and bump crate version in preparation for release (last bump was not committed)
if you want to merge the simple api thing as well I can rebase one or the other if thats needed
> Update imgui 

- CHANGELOG.md
- Cargo.toml
- README.md
Closes #45.
Doesn't fully address the error in #44.
> Update to imgui 0.7

- Cargo.toml
- examples/cube.rs
- examples/custom_textures.rs
- examples/hello_world.rs
- src/lib.rs
- src/simple_api.rs
Closes #54 
Contains a hack because of a bug with wgpu 0.8, fixed in https://github.com/gfx-rs/wgpu-rs/pull/900
shouldn't affect performance, does do one more copy when needed half the time (odd number of indices in index buffer).
> Update to wgpu 0.8

- Cargo.toml
- src/lib.rs
Remove this very short lived hack now that 0.8.1 is released
> remove hack and use wgpu 0.8.1

- CHANGELOG.md
- Cargo.toml
Incredibly easy upgrade. No breaking changes. :tada:
> Update `wgpu` to 0.9

- CHANGELOG.md
- Cargo.toml
- examples/hello-world.rs
- simple-api/Cargo.toml
- simple-api/src/lib.rs
> Support wgpu 0.11

- CHANGELOG.md
- Cargo.toml
- README.md
- simple-api/Cargo.toml
- src/imgui.wgsl
- src/lib.rs
wgpu-0.12 isn't out yet, but will be out shortly, so putting this PR up so we can be on top of it, and to show other people that the work has already done so they don't duplicate work.
> Update to wgpu 0.12

- src/lib.rs
I need to specify different sampler parameters per texture for my use case.
> Add sampler_desc field to TextureConfig

- CHANGELOG.md
- Cargo.toml
- README.md
- deny.toml
- examples/cube.rs
- examples/custom-texture.rs
- examples/hello-world.rs
- resources/cube.wgsl
- src/imgui.wgsl
- src/lib.rs
> Migrate to wgpu 0.13 and fall back on fifo present mode if mailbox isn't supported in examples

- CHANGELOG.md
- Cargo.toml
- examples/cube.rs
- examples/custom-texture.rs
- examples/hello-world.rs
Bump imgui version to 0.9.0. Fix examples to match.
> Bump imgui to 0.9

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
> Some Updates

- CHANGELOG.md
- Cargo.toml
closes https://github.com/Yatekii/imgui-wgpu-rs/issues/94 
cc https://github.com/benmkw/imnodes-rs/issues/6
> update to imgui 0.11

- CHANGELOG.md
- Cargo.toml
- examples/cube.rs
- src/lib.rs
> Bump `wgpu` to 0.16

- CHANGELOG.md
- Cargo.toml
- examples/cube.rs
- examples/custom-texture.rs
- examples/hello-world.rs
- src/lib.rs
> update to wgpu 0.18
